### ISSUE TITLE
Question: Can I use the script also for shared servers?

### ISSUE THREAD

**Issue by TravelTrader** [BernieO/ncupgrade#1]
Great script. But do you know if it's possible to use it on a shared server, like my web-package at all-inkl without true root access?

**Comment by BernieO** [comment]
I‘ve never tried that, but there is a good chance it might work as long as you have shell access.
Without shell access *ncupgrade* will not work.

**Comment by TravelTrader** [comment]
Okay, I will check the code tomorrow and maybe I'll try.
Of course, I have an ssh-connection.

**Comment by BernieO** [comment]
Cool, please let me know if it works.
